# Generated by Django 5.0.2 on 2024-03-07 16:43

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="surname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
